language: perl
sudo: required
before_script:
  - sudo apt-get update
  - sudo apt-get install cpanminus
# Standard Dist::Zilla, this will install a bunch of prereqs, speeding up the upgrade
  - sudo apt-get install libdist-zilla-perl
# Upgrade Dist::Zilla
  - sudo cpanm --notest Dist::Zilla
# This is not in the prereqs it seems, but the latest MooseX::Role::Parameterized is highly recommended -; let's do it for Moose as well
  - sudo cpanm --notest Moose MooseX::Role::Parameterized
# For my scripts, prefered over dzil --listdeps that is too long
  - sudo cpanm --notest Dist::Zilla::PluginBundle::RJBS
  - dzil authordeps --missing | xargs sudo cpanm --notest
script:
  - dzil test --release
