language: perl
sudo: required
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init --auto
before_script:
# This is not in the prereqs it seems, but the latest MooseX::Role::Parameterized is highly recommended -; let's do it for Moose as well
  - cpanm --notest Moose MooseX::Role::Parameterized
  - cpanm --notest Dist::Zilla::PluginBundle::RJBS
  - dzil authordeps --missing | sudo cpanm --notest
script:
  - dzil test --release
