#
# Saying language: perl will FAIL BY DEFAULT - come on guys...
#
language: c
sudo: required
before_install:
  - sudo apt-get update
  - sudo apt-get install cpanminus libdist-zilla-perl
# Upgrade Dist::Zilla
  - sudo cpanm --notest Dist::Zilla
# This is not in the prereqs it seems, but the latest MooseX::Role::Parameterized is highly recommended -; let's do it for Moose as well
  - sudo cpanm --notest Moose MooseX::Role::Parameterized
# AutoPrereqs will not see it - do not know why
  - sudo cpanm --notest Dist::Zilla::PluginBundle::RJBS
# AutoPrereqs is ok with the others
  - dzil listdeps --omit-core `perl -e 'print $];'` | xargs sudo cpanm --notest
  - dzil authordeps --missing | xargs sudo cpanm --notest
script:
  - dzil test --release
